# Generated by Django 5.2.4 on 2025-07-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_created_by_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('person_image', models.ImageField(upload_to='person_images/')),
                ('person_bio', models.CharField(blank=True, default='No biography provided.', max_length=255, null=True)),
                ('person_phone', models.CharField(max_length=20)),
                ('person_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('person_github', models.URLField(blank=True, default='', null=True)),
                ('person_linkedin', models.URLField(blank=True, default='', null=True)),
                ('person_twitter', models.URLField(blank=True, default='', null=True)),
                ('person_facebook', models.URLField(blank=True, default='', null=True)),
                ('person_instagram', models.URLField(blank=True, default='', null=True)),
                ('person_website', models.URLField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
